language: java
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
install: "./gradlew --stacktrace -PsonatypeUsername=dummy -PsonatypePassword=dummy -x signArchives assemble"
script: "./gradlew -PsonatypeUsername=dummy -PsonatypePassword=dummy check"
